### ISSUE TITLE
Folder 'foo' got uploaded to pypi. Please re-upload

### ISSUE THREAD

**Issue by rs2** [sid0/ntfs#9]
Look inside [pypi package 0.1.3](https://pypi.python.org/packages/3d/81/d1792d909ebe904472b061d4a7d90492cd79e1cd11944d437fc6ee3f5ddf/ntfsutils-0.1.3.zip#md5=6018f3bbdc94c40c799b6107a74837a2).

There's a folder `foo`.

Alternatively, on a clean system do:
```bash
pip install ntfsutils
python -c "import foo; print(foo.__file__)"
```

**Comment by sid0** [comment]
Just uploaded a new version 0.1.4 which no longer has this issue. Thanks for reporting it, and I think I completely missed the email for this. Sorry!
